In [1]:
import torch
from torch import nn

torch.device('cpu'), torch.device('cuda'), torch.device('cuda:1')

(device(type='cpu'), device(type='cuda'), device(type='cuda', index=1))

In [2]:
torch.cuda.device_count()

0

# function

In [3]:
def try_gpu(i=0):  #@save
    """如果存在，则返回gpu(i)，否则返回cpu()"""
    if torch.cuda.device_count() >= i + 1:
        return torch.device(f'cuda:{i}')
    return torch.device('cpu')

def try_all_gpus():  #@save
    """返回所有可用的GPU，如果没有GPU，则返回[cpu(),]"""
    devices = [torch.device(f'cuda:{i}')
             for i in range(torch.cuda.device_count())]
    return devices if devices else [torch.device('cpu')]

try_gpu(), try_gpu(10), try_all_gpus()

(device(type='cpu'), device(type='cpu'), [device(type='cpu')])

In [4]:
x = torch.tensor([1, 2, 3])
x.device

device(type='cpu')

In [5]:
X = torch.ones(2, 3, device=try_gpu())
X

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [6]:
Y = torch.rand(2, 3, device=try_gpu(1))
Y

tensor([[0.1740, 0.4747, 0.2923],
        [0.8387, 0.9123, 0.3341]])

In [7]:
net = nn.Sequential(nn.Linear(3, 1))
net = net.to(device=try_gpu())

In [8]:
net(X)

tensor([[0.9769],
        [0.9769]], grad_fn=<AddmmBackward0>)

In [9]:
net[0].weight.data.device

device(type='cpu')